### ISSUE TITLE
收集报错信息，优化报错日志

### ISSUE THREAD

**Issue by quhongwei** [alipay/rdf-file#1]

**Comment by yangfjiahl** [comment]
Caused by: com.alipay.rdf.file.exception.RdfFileException: Extension name == null
	at com.alipay.rdf.file.util.RdfFileUtil.assertTrimNotBlank(RdfFileUtil.java:120) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.loader.ExtensionLoader.getExtension(ExtensionLoader.java:59) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.meta.FileColumnTypeMeta.tryValueOf(FileColumnTypeMeta.java:50) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.loader.TemplateLoader.parseFileColumn(TemplateLoader.java:237) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.loader.TemplateLoader.load(TemplateLoader.java:130) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.loader.TemplateLoader.load(TemplateLoader.java:78) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.common.ProtocolFileValidator.init(ProtocolFileValidator.java:36) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.common.ProtocolFileValidator.init(ProtocolFileValidator.java:30) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.loader.FileToolLoader.loader(FileToolLoader.java:30) ~[rdf-file-core-2.1.20180727.jar:?]
	at com.alipay.rdf.file.interfaces.FileFactory.createValidator(FileFactory.java:79) ~[rdf-file-core-2.1.20180727.jar:?]

报错原因看不出来，最终排查下来是因为模板错误，有一个column里面有2个||
