### ISSUE TITLE
Sftp 远程文件路径问题

### ISSUE THREAD

**Issue by xingguang2013** [alipay/rdf-file#41]
在 `Windows` 环境下载 `Linux` 环境的文件时，测试发现 `com.alipay.rdf.file.storage.FileSftpStorage#listAllFiles(java.lang.String, com.alipay.rdf.file.interfaces.FileStorage.FilePathFilter...)` 功能存在问题，该方法中会处理系统文件分隔符， `com.alipay.rdf.file.util.RdfFileUtil#combinePath` 组装文件路径时会把远程 `Linux` 的文件系统分隔符替换成Windows的文件系统分隔符，导致远程文件不存在，比如 `/root` 目录下存在 `test` 文件夹，但通过上面的方法，显示组装成 `/root/test` ，然后将分隔符替换成 `\`，变成 `\root\test` ，之后就会报文件不存在。

方法调用过程为 `com.alipay.rdf.file.util.RdfFileUtil#combinePath` => `com.alipay.rdf.file.util.FileNameUtils#join(java.lang.Object[], java.lang.String)` => `com.alipay.rdf.file.util.FileNameUtils#normalize`
本人经测试是有问题的，请核实

**Comment by quhongwei** [comment]
确实会， 分隔符会根据系统自动识别， 用windows构建的路径扫描linux的文件会有问题，系统最好统一， 我们也不太好处理

**Comment by xingguang2013** [comment]
感谢，期待

**Comment by quhongwei** [comment]
我们针对你提出的问题进行了处理， 但是我们没有windows环境， 可否拉下下面这个分支打个包，在你们环境测试下， 如果ok我们后面合到master并发布新的版本
https://github.com/KloIm/rdf-file/tree/sftppathfix

**Comment by xingguang2013** [comment]
感谢，我这就试试

**Comment by xingguang2013** [comment]
经测试还是没有解决，主要是 `com.alipay.rdf.file.util.SFTPHelper#listAllFiles` 方法的152行出现问题。因为 `dir` 远程参数路径由 `/root/test` 变成了 `\root\test` ，这个是由 `com.alipay.rdf.file.util.SFTPHelper#listAllFiles` 这个方法的158行的 `com.alipay.rdf.file.util.RdfFileUtil#combinePath` 还是会将远程文件的后续目录拼接文件系统分隔符时，被替换了。

**Comment by iminright** [comment]
> RdfFileUtil
所以经过158行RdfFileUtil#combinePath后路径变成了\root\test/这样,导致了失败。
你说的是这个意思么?

**Comment by xingguang2013** [comment]
是的

**Comment by iminright** [comment]
> 是的
再试试呢,我们这边搞不到客户端服务端异构,刚好就让你们帮我们测试拉,哈哈哈

**Comment by xingguang2013** [comment]
刚测试了下，这次是可以了，麻烦再问下，`com.alipay.rdf.file.interfaces.FileStorage#copy` 这个方法的目的是从远程服务器下载文件到本地临时目录中，然后再从本地临时目录中上传到远程服务器的目标文件中这个用意是什么，感觉和 `com.alipay.rdf.file.interfaces.FileStorage#download` 最终目的是一样的。而且 `com.alipay.rdf.file.interfaces.FileStorage#copy` 使用到了临时目录，在不配置临时目录时，会出现本地临时目录为 `"/tmp/rdf-file/sftp"` , 这个目录在windows上是无效的，在执行过程中判断该目录不存在时会进行目录创建，位置 `com/alipay/rdf/file/util/SFTPHelper.java:45行` 会认为目录存在，后续在执行下载文件时，报错信息基本为文件不存在。

相关错误信息：
```java
Exception in thread "main" com.alipay.rdf.file.exception.RdfFileException: rdf-file#FileSftpStorage.copy,sftp copy fail，srcFile=/root/test/xx.txt,toFile=/root/test/yy.txt
	at com.alipay.rdf.file.storage.FileSftpStorage.copy(FileSftpStorage.java:57)
	at com.chc.SftpTest.main(SftpTest.java:23)
Caused by: 4: 
	at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:1003)
	at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:892)
	at com.alipay.rdf.file.operation.SftpOperationFactory$4.doBusiness(SftpOperationFactory.java:209)
	at com.alipay.rdf.file.operation.SftpOperationFactory$5.doBusiness(SftpOperationFactory.java:255)
	at com.alipay.rdf.file.operation.AbstractSftpOperationTemplate.handle(AbstractSftpOperationTemplate.java:69)
	at com.alipay.rdf.file.storage.FileSftpStorage.copy(FileSftpStorage.java:53)
	... 1 more
Caused by: java.io.FileNotFoundException: D:\github\rdf-file-windows\tmp\rdf-file\sftp\xx.txt(系统找不到指定的路径。)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:979)
	... 6 more
Disconnected from the target VM, address: '127.0.0.1:58455', transport: 'socket'

Process finished with exit code 1

```

**Comment by iminright** [comment]
明天看看




| |
piaokcd@163.com
|
|
邮箱：piaokcd@163.com
|

Signature is customized by Netease Mail Master

在2019年09月04日 22:52，Nthan 写道：

刚测试了下，这次是可以了，麻烦再问下，com.alipay.rdf.file.interfaces.FileStorage#copy 这个方法的目的是从远程服务器下载文件到本地临时目录中，然后再从本地临时目录中上传到远程服务器的目标文件中这个用意是什么，感觉和 com.alipay.rdf.file.interfaces.FileStorage#download 最终目的是一样的。而且 com.alipay.rdf.file.interfaces.FileStorage#copy 使用到了临时目录，在不配置临时目录时，会出现本地临时目录为 "/tmp/rdf-file/sftp" , 这个目录在windows上是无效的，在执行过程中判断该目录不存在时会进行目录创建，位置 com/alipay/rdf/file/util/SFTPHelper.java:45行 会认为目录存在，后续在执行下载文件时，报错信息基本为文件不存在。

相关错误信息：

Exception in thread "main"com.alipay.rdf.file.exception.RdfFileException: rdf-file#FileSftpStorage.copy,sftp copy fail，srcFile=/root/test/xx.txt,toFile=/root/test/yy.txt

	at com.alipay.rdf.file.storage.FileSftpStorage.copy(FileSftpStorage.java:57)

	at com.chc.SftpTest.main(SftpTest.java:23)

Caused by:4: 

	at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:1003)

	at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:892)

	at com.alipay.rdf.file.operation.SftpOperationFactory$4.doBusiness(SftpOperationFactory.java:209)

	at com.alipay.rdf.file.operation.SftpOperationFactory$5.doBusiness(SftpOperationFactory.java:255)

	at com.alipay.rdf.file.operation.AbstractSftpOperationTemplate.handle(AbstractSftpOperationTemplate.java:69)

	at com.alipay.rdf.file.storage.FileSftpStorage.copy(FileSftpStorage.java:53)

	...1 more

Caused by:java.io.FileNotFoundException:D:\github\rdf-file-windows\tmp\rdf-file\sftp\xx.txt(系统找不到指定的路径。)

	at java.io.FileOutputStream.open0(NativeMethod)

	at java.io.FileOutputStream.open(FileOutputStream.java:270)

	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)

	at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:979)

	...6 more

Disconnected from the target VM, address:'127.0.0.1:58455', transport:'socket'Process finished with exit code 1

**Comment by xingguang2013** [comment]
还有一个建议是，`SftpProgressMonitor` 接口的实现类 `com.alipay.rdf.file.util.SFTPLogMonitor` 目前支持上传文件的总大小，下载无法获取，值为 '0'，那么在下载操作中，建议就不要显示在日志中，以免造成误解。
再有就是 `SftpProgressMonitor` 是按照 `Jsch` 对文件缓冲块来回调的，如果文件过大，日志打印频率是否过高？是否可以改成其中有个定时任务 `Executors.newSingleThreadScheduledExecutor()`，按照一定的时间间隔来打印(比如每隔3秒)日志。下载完成时，关闭定时任务线程池。

还有就是显示进度，总是以 `bytes` 字节显示文件进度大小，文件太大时难以阅读，改成数值超过1024就换个单位，如 `KiB` `MiB` `GiB` `TiB`等？

**Comment by iminright** [comment]
> 还有一个建议是，`SftpProgressMonitor` 接口的实现类 `com.alipay.rdf.file.util.SFTPLogMonitor` 目前支持上传文件的总大小，下载无法获取，值为 '0'，那么在下载操作中，建议就不要显示在日志中，以免造成误解。
> 再有就是 `SftpProgressMonitor` 是按照 `Jsch` 对文件缓冲块来回调的，如果文件过大，日志打印频率是否过高？是否可以改成其中有个定时任务 `Executors.newSingleThreadScheduledExecutor()`，按照一定的时间间隔来打印(比如每隔3秒)日志。下载完成时，关闭定时任务线程池。
> 
> 还有就是显示进度，总是以 `bytes` 字节显示文件进度大小，文件太大时难以阅读，改成数值超过1024就换个单位，如 `KiB` `MiB` `GiB` `TiB`等？

> 新增com.alipay.rdf.file.util.SFTPLogMonitorAtFixedRate实现,通过com.alipay.rdf.file.storage.SftpConfig#progressLogPrintTypeEnum选择实现方式,com.alipay.rdf.file.storage.SftpConfig#progressPrintLogPeriod控制打印进度日志周期;进度大小已经格式化处理;下载不再显示原文件大小;效果如下:
Thu Sep 05 15:11:22 CST 2019:::rdf-file#SFTPLogMonitorAtFixedRate.count[上传操作],文件大小：{95.4 MiB},当前进度：{31.8 KiB}
Thu Sep 05 15:11:23 CST 2019:::rdf-file#SFTPLogMonitorAtFixedRate.count[上传操作],文件大小：{95.4 MiB},当前进度：{92.2 MiB}
> com.alipay.rdf.file.storage.SftpConfig#DEFAULT_LOCAL_TMP_PATH使用System.getProperty("java.io.tmpdir")替代

升级rdf-file-sftp,rdf-file-core至2.2.4

**Comment by xingguang2013** [comment]
感谢，都已测试通过了

**Comment by xingguang2013** [comment]
com/alipay/rdf/file/util/RdfFileUtil.java:764 行，有个错别字，应该是 1024 不是 1014 吧？

**Comment by iminright** [comment]
> com/alipay/rdf/file/util/RdfFileUtil.java:764 行，有个错别字，应该是 1024 不是 1014 吧？

好的，多谢提醒
