### ISSUE TITLE
合并额外空文件时错误

### ISSUE THREAD

**Issue by iminright** [alipay/rdf-file#48]
oss合并额外已存全文件数据为空时错误
com.alipay.rdf.file.exception.RdfFileException: rdf-file#FileOssStorage.getInputStream(filePath=rdf/rdf-file/open/PreheatMergeDeFileTest/testMergeEmpty/1, start=96, length=0获取数据长度必须大于零
	at com.alipay.rdf.file.storage.FileOssStorage.getInputStream(FileOssStorage.java:109)
	at com.alipay.rdf.file.common.IOFactory.createReader(IOFactory.java:37)
	at com.alipay.rdf.file.common.ProtocolFileReader.ensureOpen(ProtocolFileReader.java:300)
	at com.alipay.rdf.file.common.ProtocolFileReader.readBodyLine(ProtocolFileReader.java:251)
	at com.alipay.rdf.file.common.ProtocolFileMerger.mergeBodyLines(ProtocolFileMerger.java:276)
	at com.alipay.rdf.file.common.ProtocolFileMerger.mergeBody(ProtocolFileMerger.java:145)
	at com.alipay.rdf.file.common.ProtocolFileMerger.merge(ProtocolFileMerger.java:83)

**Comment by quhongwei** [comment]
release by 2.2.5
